# Configurations
title:            Xander's Notebook
longtitle:        Xander's Notebook

remote_theme:     sighingnow/jekyll-gitbook
syntax_highlighter_style: github

github_username:  XanderBert
facebook: false
twitter: false